services:
    rackruether_product.listener.insert_tags:
        class: RackRuether\ProductBundle\EventListener\InsertTagsListener
        arguments:
            - "@contao.framework"
        tags:
            - { name: contao.hook, hook: replaceInsertTags }
        public: true