services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    rackruether_product.picker.product_provider:
        class: RackRuether\ProductBundle\Picker\ProductPickerProvider
        arguments:
            - "@knp_menu.factory"
            - "@router"
            - "@translator"
        calls:
            - [setTokenStorage, ["@security.token_storage"]]
        tags:
            - { name: contao.picker_provider, priority: 256 }
